# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
n = np.random.random((3,3,3))
print(n)
print("The shape of array n is: ")
print(n.shape)

[[[0.01222568 0.08952853 0.64258727]
  [0.95591924 0.78253517 0.42364712]
  [0.95290901 0.89750845 0.17192696]]

 [[0.32668096 0.91432784 0.42849472]
  [0.59236558 0.24119632 0.59121098]
  [0.2348491  0.51415649 0.71885519]]

 [[0.87654847 0.24684867 0.97871641]
  [0.17500173 0.18869938 0.16447448]
  [0.2768359  0.51612545 0.79260195]]]
The shape of array n is: 
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
n = np.diag(1+np.arange(4), k = -1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
a = np.zeros ((8,8), dtype=int)
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [15]:
import numpy as np
N = np.random.random((5,5))
print("Original matrix of size 5X5: ")
print(N)
Nmax, Nmin = N.max(), N.min()
N = (N - Nmin) / (Nmax - Nmin)
print("Normalized matrix: ")
print(N)

Original matrix of size 5X5: 
[[0.44337977 0.62056741 0.13979032 0.93663806 0.15293196]
 [0.75079081 0.67507154 0.80987062 0.30072309 0.84346471]
 [0.54861538 0.91845157 0.88181159 0.60050127 0.65743881]
 [0.58151645 0.35890633 0.27580186 0.35264124 0.46915539]
 [0.79945848 0.83092621 0.99045493 0.31069904 0.24697937]]
Normalized matrix: 
[[0.35688501 0.56517819 0.         0.9367355  0.01544867]
 [0.7182625  0.6292506  0.78771386 0.18918475 0.82720543]
 [0.48059488 0.91535634 0.87228416 0.54158941 0.60852242]
 [0.51927178 0.25758214 0.15988855 0.25021721 0.38718558]
 [0.77547384 0.81246578 1.         0.20091199 0.12600624]]


# 5.  How to find common values between two arrays?

In [18]:
import numpy as np
print("Array 1 is: ")
a1 = np.array([10,15,20,25,30,40])
print(a1)
print("Array 2 is :")
a2 = np.array([20,30,40])
print(a2)
common_values = np.intersect1d(a1, a2)
print("Common values between two arrays are :")
print(common_values)

Array 1 is: 
[10 15 20 25 30 40]
Array 2 is :
[20 30 40]
Common values between two arrays are :
[20 30 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [19]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday's date: ",yesterday)
today = np.datetime64('today', 'D')
print("Today's date: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date : ",tomorrow)

Yesterday's date:  2020-07-27
Today's date:  2020-07-28
Tomorrow's date :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [20]:
import numpy as np
m = np.array([5,10,15])
print(m)
n = np.array([5,10,15])
print(n)
comparison = m == n
equal_arrays = comparison.all()
print("Output is True if two arrays are equal")
print("Output is False if two arrays are equal")
print("Output:",equal_arrays)

[ 5 10 15]
[ 5 10 15]
Output is True if two arrays are equal
Output is False if two arrays are equal
Output: True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [21]:
import numpy as np
x = np.random.random(10)
print("Original array of size 10 :")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array of size 10 :
[0.99016739 0.36155182 0.40180485 0.87773205 0.88338213 0.77654415
 0.9961374  0.98772108 0.36607231 0.1308741 ]
Maximum value replaced by 0:
[0.99016739 0.36155182 0.40180485 0.87773205 0.88338213 0.77654415
 0.         0.98772108 0.36607231 0.1308741 ]


# 9. How to print all the values of an array?

In [22]:
import numpy as np
import sys
num = np.arange(500)
np.set_printoptions(threshold = sys.maxsize)
print(num)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

# 10.Subtract the mean of each row of a matrix

In [24]:
import numpy as np
print("Original matrix: \n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the given matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix: 

[[0.82463822 0.72602072 0.84663134 0.43256535 0.34497168 0.1751015
  0.47897526 0.25458379 0.59227095 0.63299067]
 [0.12445021 0.13921636 0.91647116 0.78381795 0.6953076  0.09070258
  0.91852042 0.50941163 0.81363761 0.21088759]
 [0.08464011 0.93853315 0.63872221 0.93272224 0.48403729 0.01397352
  0.66655357 0.57939899 0.76941995 0.84151808]
 [0.72116665 0.22695945 0.42992415 0.73681609 0.47805059 0.5448642
  0.33543479 0.66108986 0.28170715 0.64832268]
 [0.02276366 0.81515274 0.4837804  0.18829913 0.91142242 0.78486702
  0.17945886 0.83740965 0.50504822 0.00801096]]

Subtract the mean of each row of the given matrix:

[[ 0.29376327  0.19514577  0.31575639 -0.0983096  -0.18590327 -0.35577345
  -0.05189969 -0.27629115  0.061396    0.10211573]
 [-0.3957921  -0.38102595  0.39622885  0.26357564  0.17506529 -0.42953973
   0.39827811 -0.01083068  0.2933953  -0.30935472]
 [-0.5103118   0.34358124  0.0437703   0.33777033 -0.11091462 -0.58097839
   0.07160166 -0.01555292  0.1

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [26]:
n = np.random.rand(20, 1)
print("The original vector is: \n")
print(n)
index_a = np.random.randint(0,len(n),4)
print("The Index values are:")
print(index_a)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(n,index_a,1)
print(n)

The original vector is: 

[[0.31360871]
 [0.7183027 ]
 [0.28535619]
 [0.87767993]
 [0.4337032 ]
 [0.15295599]
 [0.70625398]
 [0.40762743]
 [0.03977784]
 [0.84671615]
 [0.80681244]
 [0.41686447]
 [0.92534002]
 [0.73721095]
 [0.375248  ]
 [0.31659115]
 [0.25276195]
 [0.45803868]
 [0.5683773 ]
 [0.09578944]]
The Index values are:
[14  2 11  1]
Final vector after adding 1 to corresponding elements at the specified indices:
[[0.31360871]
 [1.7183027 ]
 [1.28535619]
 [0.87767993]
 [0.4337032 ]
 [0.15295599]
 [0.70625398]
 [0.40762743]
 [0.03977784]
 [0.84671615]
 [0.80681244]
 [1.41686447]
 [0.92534002]
 [0.73721095]
 [1.375248  ]
 [0.31659115]
 [0.25276195]
 [0.45803868]
 [0.5683773 ]
 [0.09578944]]


# 12.How to get the diagonal of a dot product?

In [27]:
a = np.random.randn(4,4)
print("The first 4X4 array is: ")
print(a)
b = np.random.randn(4,4)
print("The second 4X4 array is: ")
print(b)
c = np.dot(a,b)
print("The corresponding dot product is- ")
print(c)
z = np.diag(c)
print("The corresponding diagnol elements are- ")
print(z)

The first 4X4 array is: 
[[ 0.8101159  -1.17405913  1.36814786 -0.49556621]
 [-2.160506   -0.84692018  0.70478362 -0.97540648]
 [-0.00716388  0.09242871 -2.5539567  -1.12779292]
 [ 0.41529421  1.14071617  1.75004521  1.21037635]]
The second 4X4 array is: 
[[-0.32926677 -0.31388414  1.51500056  0.58988201]
 [ 0.36614958 -0.31368372 -0.3172264  -0.63571354]
 [ 0.64376138 -1.29544703  0.63137194  0.59200144]
 [ 1.32589527 -0.94564169 -0.65922353 -0.25795345]]
The corresponding dot product is- 
[[-0.47293365 -1.18973431  2.79026767  2.16201659]
 [-0.438291    0.95318884 -1.91651086 -0.06720261]
 [-3.10327242  4.34825887 -0.90920308 -1.28401201]
 [ 3.01237396 -3.89985157  0.57432656  0.24361441]]
The corresponding diagnol elements are- 
[-0.47293365  0.95318884 -0.90920308  0.24361441]


# 13.How to find the most frequent value in an array?

In [29]:
k=np.array([1,2,3,3,5,3,6,6,7,6,6,8,9,10,10,11,12])
np.argmax(np.bincount(k))

6

# 14.How to get the n largest values of an array

In [31]:
M = np.arange(500)
np.random.shuffle(M)
n = int(input("Enter the value of n:"))
print("The",n,"largest value of the array are:")
print (M[np.argpartition(-M,n)[:n]])

Enter the value of n:50
The 50 largest value of the array are:
[453 489 491 461 494 471 464 469 462 479 488 496 492 480 486 452 470 498
 483 459 482 476 468 493 467 477 487 478 499 474 485 497 456 466 472 463
 481 454 457 490 465 473 455 458 495 484 460 475 451 450]


# 15.How to create a record array from a regular array?

In [36]:
reg_arr = np.array([["Divyaraj", 88.5, 90],["Aarav", 87, 99],["Vijay", 85.5, 91]])
print("Original array:")
print(reg_arr)
print("\nRecord array:")
rec_arr = np.core.records.fromarrays(reg_arr.T,names='col1, col2, col3',formats = 'S80, f8, i8')
print(rec_arr)

Original array:
[['Divyaraj' '88.5' '90']
 ['Aarav' '87' '99']
 ['Vijay' '85.5' '91']]

Record array:
[(b'Divyaraj', 88.5, 90) (b'Aarav', 87. , 99) (b'Vijay', 85.5, 91)]
